### day2
### create 10 usr and set random password for them, the passwords will be recorded in a files named 'usrinfo.txt'
### usr name from 'usr_00' to 'usr+09'
### password requirements: contains lower and upper case letters and numbers, password length == 15

#################################################################################

#!/bin/bash
#author: nemo
#version: v1
#date: 2024-08-19 

## check if /DATACENTER1/zixing.liao/try_something/shellPrac/day2/usrinfo.txt exists, then we will delete it or it can have influence on out bash
if [[ -f /DATACENTER1/zixing.liao/try_something/shellPrac/day2/usrinfo.txt]]
then 
	rm /DATACENTER1/zixing.liao/try_something/shellPrac/day2/usrinfo.txt
fi

## check if command mkpasswd availible, we use this command to generate usr password
if ! which mkpasswd
then 
	## we assume that the system is ubuntu/debian, we use apt-get
	apt-get install -y expect
fi

for i in $(seq -f "%02g" 0 9)
do
	## randomly generate a string each time, which is this usr's password.
	## password that generated by `mkpasswd` would contain lower and upper case letters, numbers and special symbols by default.
	## if you don't want special symbols, add `-s 0` to strict
	p=$(mkpasswd -l 15)
	## add usrs, and set password
	useradd user_${i} && echo "${p}" | passwd --stdin user_${i}
	echo "user_${i} ${p}" >> /DATACENTER1/zixing.liao/try_something/shellPrac/day2/usrinfo.txt
done


